### ISSUE TITLE
Problem with Rendering and getting a snapshot

### ISSUE THREAD

**Issue by BasicSeal** [MarkSlat/OctoPrint-Hologram#5]
I have installed the plugin, and put in the dimentions. but i get the same errors. I also installed a newer version of numby.
I am on a windows 11 mashine
![Screenshot 2024-05-23 172149](https://github.com/MarkSlat/OctoPrint-Hologram/assets/125978698/6b977823-3672-4dbd-ac68-2504bd31f204)

**Comment by MarkSlat** [comment]
That looks to be an issue snapshot URL/camera access. Have you set a custom URL for your camera stream or are you using the one provided with the classic camera plugin?

**Comment by BasicSeal** [comment]
So i need to set a stream URL for the webcam, i have not currently set one. Is a webcam required fopr this plugin?

**Comment by MarkSlat** [comment]
I think if there is one currently set up it should be able to access it. If you go into the classic web camera plugin and test the stream and snapshot function. There should be a URL in there as well.

**Comment by MarkSlat** [comment]
Oh sorry, yes a camera is required for this plugin. It's designed use the webcam to take a snapshot and then overlay the render on top of it.

**Comment by BasicSeal** [comment]
is there a way, i can just take a still imgage instead of the snapshot?

**Comment by BasicSeal** [comment]
If i connect a camera to octoprint, the snapshot url and the stream works, but i still get the same error message

**Comment by MarkSlat** [comment]
Ok thats strange would you be able to provide the plugins log and the snapshot's url?

**Comment by BasicSeal** [comment]
I am using : "http://192.168.178.136:8888/" as the snapshot url
I hope this is the right log, but thanks for your help so far
[plugin_pluginmanager_console.log](https://github.com/MarkSlat/OctoPrint-Hologram/files/15420020/plugin_pluginmanager_console.log)

**Comment by MarkSlat** [comment]
Sorry I am only getting back to you now I was away for the last few days. Is this a custom implementation for the camera stream and does the URL provide an actually image back. For example I have set up "http://localhost:5001/webcam/?action=snapshot" for a snapshot and http://localhost:5001/webcam for streaming.

**Comment by BasicSeal** [comment]
this is the stream and snapshot url from a porgramm called Yamcam and it does provide feedback, but just doenst work for the plugin

**Comment by MarkSlat** [comment]
I am not sure how the plugin handles external applications, are other plugins able to retrieve a snapshot?

**Comment by BasicSeal** [comment]
i dont have any plugins that use snaphots beside that one

**Comment by BasicSeal** [comment]
right now, it suddenly worked with an external image as a snaphot url, Thank you

**Comment by MarkSlat** [comment]
Oh nice, you happy for me to mark this as resolved?
